global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'booking'
    static_configs:
      - targets: ['booking:5000']
  - job_name: 'payment'
    static_configs:
      - targets: ['payment:5000']
  - job_name: 'user'
    static_configs:
      - targets: ['user:5000']
