global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'user-service'
    static_configs:
      - targets: ['user:5000']

  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment:5000']

  - job_name: 'booking-service'
    static_configs:
      - targets: ['booking:5000']
